buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
    }
}

apply plugin: 'com.android.application'

android {
    namespace 'com.yourubapro.keypad'
    compileSdkVersion 33
    defaultConfig {
        applicationId "com.yourubapro.keypad"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
    }
}

repositories {
    google()
    mavenCentral()
}