plugins {
    id 'com.android.application' version '8.2.0'
}

android {
    namespace 'com.yourubapro.keypad'
    compileSdk 34

    defaultConfig {
        applicationId "com.yourubapro.keypad"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

repositories {
    google()
    mavenCentral()
}
